command:
  - streamlit
  - run
  - app.py
  - --server.port
  - "8000"
  - --server.address
  - "0.0.0.0"

env:
  - name: WAREHOUSE_ID
    valueFrom: sql-warehouse

  - name: VECTOR_SEARCH_INDEX
    valueFrom: vector-search-index